[phases.setup]
nixPkgs = ["python310", "pip", "libgcc"]
aptPkgs = []

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "cd ml && python3 -m pip install -r requirements.txt"
]

[start]
cmd = "cd ml && python3 -m uvicorn inference_api:app --host 0.0.0.0 --port $PORT"
